export const ADD_NEW_COLUMN = "ADD_NEW_COLUMN";
export const UPDATE_COLUMN = "UPDATE_COLUMN";
export const DELETE_COLUMN = "DELETE_COLUMN";

export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";

export const UPDATE_TASK_LIST = "UPDATE_TASK_LIST";